/*
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class AlphanumericPINTextField;

@interface AlphanumericPINTableViewCell : UITableViewCell {

	AlphanumericPINTextField* _pinTextField;

}

@property (nonatomic,retain) AlphanumericPINTextField * pinTextField;              //@synthesize pinTextField=_pinTextField - In the implementation block
-(void)dealloc;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(id)pinTextField;
-(void)setPinTextField:(AlphanumericPINTextField *)arg1 ;
@end

