/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/Preferences-Structs.h>
#import <Preferences/PINView.h>

<<<<<<< HEAD
@class UITextField, AlphanumericPINTableViewCell, UITableView, NSString;
=======
@class UITextField, AlphanumericPINTableViewCell, UITableView;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8

@interface AlphanumericPINView : PINView <UITableViewDataSource> {

	UITextField* _passcodeField;
	AlphanumericPINTableViewCell* _cell;
	UITableView* _table;

}
<<<<<<< HEAD

@property (readonly) NSUInteger hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
=======
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
<<<<<<< HEAD
-(BOOL)resignFirstResponder;
-(BOOL)becomeFirstResponder;
-(void)appendString:(id)arg1 ;
-(BOOL)isFirstResponder;
-(BOOL)canBecomeFirstResponder;
=======
-(void)appendString:(id)arg1 ;
-(BOOL)resignFirstResponder;
-(BOOL)becomeFirstResponder;
-(BOOL)canBecomeFirstResponder;
-(BOOL)isFirstResponder;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(BOOL)keyboardInputChanged:(id)arg1 ;
-(BOOL)textFieldShouldReturn:(id)arg1 ;
-(id)stringValue;
-(void)setStringValue:(id)arg1 ;
-(void)deleteLastCharacter;
-(void)setBlocked:(BOOL)arg1 ;
<<<<<<< HEAD
-(void)setTextFieldKeyboardType:(int)arg1 ;
-(void)setTextFieldKeyboardAppearance:(int)arg1 ;
=======
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)showError:(id)arg1 animate:(BOOL)arg2 ;
-(void)hidePasscodeField:(BOOL)arg1 ;
-(void)okButtonPressed:(id)arg1 ;
@end

