/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/Preferences-Structs.h>
#import <Preferences/PSEditingPane.h>
#import <Preferences/PSPINEntryViewDelegate.h>

@protocol PINEntryView;
@class UITransitionView, UIView, UIKeyboard, NSString;

@interface DevicePINPane : PSEditingPane <UIKeyInput, UITextInputTraits, PSPINEntryViewDelegate> {

	UITransitionView* _transitionView;
	BOOL _transitioning;
	UIView* _pinView;
	UIKeyboard* _keypad;
	BOOL _keypadActive;
	int _autocapitalizationType;
	int _autocorrectionType;
	int _keyboardType;
	int _keyboardAppearance;
	BOOL _playSound;
	BOOL _isBlocked;
	BOOL _simplePIN;

}

@property (nonatomic,retain) UIView* pinView;                              //@synthesize pinView=_pinView - In the implementation block
@property (readonly) NSUInteger hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) UITextAutocapitalizationType autocapitalizationType;                                 //@synthesize autocapitalizationType=_autocapitalizationType - In the implementation block
@property (assign,nonatomic) UITextAutocorrectionType autocorrectionType;                                     //@synthesize autocorrectionType=_autocorrectionType - In the implementation block
@property (assign,nonatomic) UITextSpellCheckingType spellCheckingType; 
@property (assign,nonatomic) UIKeyboardType keyboardType;                                           //@synthesize keyboardType=_keyboardType - In the implementation block
@property (assign,nonatomic) UIKeyboardAppearance keyboardAppearance;                                     //@synthesize keyboardAppearance=_keyboardAppearance - In the implementation block
@property (assign,nonatomic) UIReturnKeyType returnKeyType; 
@property (assign,nonatomic) BOOL enablesReturnKeyAutomatically; 
@property (assign,getter=isSecureTextEntry,nonatomic) BOOL secureTextEntry; 
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setTitle:(id)arg1 ;
-(BOOL)resignFirstResponder;
-(BOOL)becomeFirstResponder;
-(id)text;
-(void)setText:(id)arg1 ;
-(BOOL)canBecomeFirstResponder;
-(void)transitionViewDidComplete:(id)arg1 ;
-(UIKeyboardAppearance)keyboardAppearance;
-(BOOL)hasText;
-(void)insertText:(id)arg1 ;
-(void)deleteBackward;
-(BOOL)isSecureTextEntry;
-(UITextAutocapitalizationType)autocapitalizationType;
-(void)setAutocapitalizationType:(UITextAutocapitalizationType)arg1 ;
-(UITextAutocorrectionType)autocorrectionType;
-(void)setAutocorrectionType:(UITextAutocorrectionType)arg1 ;
-(UIKeyboardType)keyboardType;
-(void)setKeyboardType:(UIKeyboardType)arg1 ;
-(void)setKeyboardAppearance:(UIKeyboardAppearance)arg1 ;
-(id)password;
-(BOOL)requiresKeyboard;
-(id)specifierLabel;
-(void)deactivateKeypadView;
-(void)dismissKeypad;
-(void)showFailedAttempts:(long)arg1 ;
-(void)showError:(id)arg1 error:(id)arg2 isBlocked:(BOOL)arg3 animate:(BOOL)arg4 ;
-(void)hideFailedAttempts;
-(void)hideError;
-(void)setPINPolicyString:(id)arg1 visible:(BOOL)arg2 ;
-(BOOL)simplePIN;
-(void)okButtonPressed;
-(void)slideToNewPasscodeField:(BOOL)arg1 requiresKeyboard:(BOOL)arg2 numericOnly:(BOOL)arg3 ;
-(void)setSimplePIN:(BOOL)arg1 requiresKeyboard:(BOOL)arg2 numericOnly:(BOOL)arg3 ;
-(void)pinView:(id)arg1 pinValueChanged:(id)arg2 ;
-(void)pinView:(id)arg1 pinEntered:(id)arg2 ;
-(void)_setPlaysKeyboardClicks:(BOOL)arg1 ;
-(UIView*)pinView;
-(void)setPinView:(UIView*)arg1 ;
-(void)setKeyboardIsNumeric:(BOOL)arg1 ;
-(void)_setKeypadState:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)activateKeypadView;
-(void)setKeyboardUserInteractionEnabled:(BOOL)arg1 ;
-(void)delayForTextEntryAnimationsWithCompletion:(/*^block*/ id)arg1 ;
-(void)setSimplePIN:(BOOL)arg1 requiresKeyboard:(BOOL)arg2 ;
-(void)slideToNewPasscodeField:(BOOL)arg1 withKeyboard:(BOOL)arg2 ;
-(void)clearPassword;
@end
