/*
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol KeychainSyncViewControllerDelegate <NSObject>
@optional
-(void)keychainSyncControllerCancel:(id)arg1;

@required
-(void)keychainSyncController:(id)arg1 didFinishWithResult:(id)arg2 error:(id)arg3;
@end

