/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/KeychainSyncTextEntryController.h>

@class UIButton, UIAlertView, NSString, PSKeychainSyncManager;

@interface KeychainSyncSMSVerificationController : KeychainSyncTextEntryController <UIAlertViewDelegate> {

	UIButton* _footerButton;
	UIAlertView* _supportVerificationAlert;
	NSString* _phoneNumber;
	NSString* _dialingPrefix;
	NSString* _countryCode;
	unsigned _verificationCodeLength;
	PSKeychainSyncManager* _keychainSyncManager;

}

@property (nonatomic,retain) NSString * phoneNumber;                                   //@synthesize phoneNumber=_phoneNumber - In the implementation block
@property (nonatomic,retain) NSString * dialingPrefix;                                 //@synthesize dialingPrefix=_dialingPrefix - In the implementation block
@property (nonatomic,retain) NSString * countryCode;                                   //@synthesize countryCode=_countryCode - In the implementation block
@property (assign,nonatomic) unsigned verificationCodeLength;                          //@synthesize verificationCodeLength=_verificationCodeLength - In the implementation block
@property (assign,nonatomic) PSKeychainSyncManager * keychainSyncManager;              //@synthesize keychainSyncManager=_keychainSyncManager - In the implementation block
<<<<<<< HEAD
@property (readonly) NSUInteger hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
=======
-(void)setPhoneNumber:(NSString *)arg1 ;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)dealloc;
-(id)init;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2 ;
-(void)viewDidLayoutSubviews;
-(void)loadView;
<<<<<<< HEAD
-(NSString *)phoneNumber;
-(void)setCountryCode:(NSString *)arg1 ;
-(void)setDialingPrefix:(NSString *)arg1 ;
-(NSString *)dialingPrefix;
-(id)specifiers;
-(void)dismissAlerts;
=======
-(id)phoneNumber;
-(void)setCountryCode:(NSString *)arg1 ;
-(id)countryCode;
-(void)setDialingPrefix:(NSString *)arg1 ;
-(id)dialingPrefix;
-(id)specifiers;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)setKeychainSyncManager:(PSKeychainSyncManager *)arg1 ;
-(void)setVerificationCodeLength:(unsigned)arg1 ;
-(unsigned)verificationCodeLength;
-(void)showSupportVerification;
<<<<<<< HEAD
-(PSKeychainSyncManager *)keychainSyncManager;
-(unsigned)numberOfPasscodeFields;
-(void)setPhoneNumber:(NSString *)arg1 ;
-(NSString *)countryCode;
=======
-(id)keychainSyncManager;
-(unsigned)numberOfPasscodeFields;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
@end

