/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:40 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/KeychainSyncTextEntryController.h>

<<<<<<< HEAD
@class NSString, UIButton, UILabel;

@interface KeychainSyncSecurityCodeController : KeychainSyncTextEntryController {

	NSString* _generatedCode;
	UIButton* _footerButton;
	UILabel* _footerLabel;
	float _keyboardHeight;
=======
@class NSString, UIButton, UIAlertView;

@interface KeychainSyncSecurityCodeController : KeychainSyncTextEntryController <UIAlertViewDelegate> {

	NSString* _generatedCode;
	BOOL _passcodeMismatch;
	UIButton* _footerButton;
	UIAlertView* _forgotSecurityCodeAlert;
	BOOL _forgotCodeAlertHasApproveButton;
	UIAlertView* _resetKeychainAlert;
	UIAlertView* _weakSecurityCodeAlert;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
	BOOL _showsAdvancedSettings;
	int _mode;
	int _securityCodeType;
	NSString* _firstPasscodeEntry;

}

@property (assign,nonatomic) int mode;                                   //@synthesize mode=_mode - In the implementation block
@property (assign,nonatomic) int securityCodeType;                       //@synthesize securityCodeType=_securityCodeType - In the implementation block
@property (assign,nonatomic) BOOL showsAdvancedSettings;                 //@synthesize showsAdvancedSettings=_showsAdvancedSettings - In the implementation block
@property (nonatomic,retain) NSString * firstPasscodeEntry;              //@synthesize firstPasscodeEntry=_firstPasscodeEntry - In the implementation block
<<<<<<< HEAD
-(id)placeholderText;
-(void)dealloc;
-(id)init;
-(void)viewDidLayoutSubviews;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)setMode:(int)arg1 ;
-(int)mode;
-(id)specifiers;
-(int)securityCodeType;
-(void)setSecurityCodeType:(int)arg1 ;
-(NSString *)firstPasscodeEntry;
=======
-(void)dealloc;
-(id)init;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2 ;
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(void)setMode:(int)arg1 ;
-(int)mode;
-(id)placeholderText;
-(id)specifiers;
-(int)securityCodeType;
-(void)setSecurityCodeType:(int)arg1 ;
-(id)firstPasscodeEntry;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)setFirstPasscodeEntry:(NSString *)arg1 ;
-(Class)textEntryCellClass;
-(id)textEntryCell;
-(void)showAdvancedOptions;
-(void)generateRandomCode;
-(void)forgotSecurityCode;
-(void)updateNextButton;
-(void)animatePasscodeFieldLeft:(BOOL)arg1 ;
-(void)textEntryViewDidChange:(id)arg1 ;
-(void)didFinishEnteringText:(id)arg1 ;
<<<<<<< HEAD
-(void)dismissAlerts;
=======
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(BOOL)showsAdvancedSettings;
-(void)setShowsAdvancedSettings:(BOOL)arg1 ;
-(void)keyboardWillShow:(id)arg1 ;
@end

