/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:10 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:43 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSKeychainSyncViewController.h>
#import <Preferences/KeychainSyncPasscodeFieldDelegate.h>

@protocol UIKeyInput;
@class PSTableCell, UIView, PSSpecifier, NSString;

@interface KeychainSyncTextEntryController : PSKeychainSyncViewController <KeychainSyncPasscodeFieldDelegate> {

	PSTableCell* _textEntryCell;
<<<<<<< HEAD
	UIView* _textEntryView;
	PSSpecifier* _textEntrySpecifier;
	BOOL _hidesNextButton;
	BOOL _secureTextEntry;
	BOOL _textFieldHasRoundBorder;
	BOOL _convertsNumeralsToASCII;
=======
	UIView<UIKeyInput>* _textEntryView;
	PSSpecifier* _textEntrySpecifier;
	BOOL _hidesNextButton;
	BOOL _secureTextEntry;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
	int _textEntryType;
	NSString* _textValue;

}

<<<<<<< HEAD
@property (assign,nonatomic) int textEntryType;                         //@synthesize textEntryType=_textEntryType - In the implementation block
@property (assign,nonatomic) BOOL hidesNextButton;                      //@synthesize hidesNextButton=_hidesNextButton - In the implementation block
@property (assign,nonatomic) BOOL secureTextEntry;                      //@synthesize secureTextEntry=_secureTextEntry - In the implementation block
@property (assign,nonatomic) BOOL textFieldHasRoundBorder;              //@synthesize textFieldHasRoundBorder=_textFieldHasRoundBorder - In the implementation block
@property (assign,nonatomic) BOOL convertsNumeralsToASCII;              //@synthesize convertsNumeralsToASCII=_convertsNumeralsToASCII - In the implementation block
@property (nonatomic,retain) NSString * textValue;                      //@synthesize textValue=_textValue - In the implementation block
@property (readonly) NSUInteger hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)textFieldChanged:(id)arg1 ;
-(id)placeholderText;
=======
@property (assign,nonatomic) int textEntryType;                 //@synthesize textEntryType=_textEntryType - In the implementation block
@property (assign,nonatomic) BOOL hidesNextButton;              //@synthesize hidesNextButton=_hidesNextButton - In the implementation block
@property (assign,nonatomic) BOOL secureTextEntry;              //@synthesize secureTextEntry=_secureTextEntry - In the implementation block
@property (nonatomic,retain) NSString * textValue;              //@synthesize textValue=_textValue - In the implementation block
-(void)textFieldChanged:(id)arg1 ;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)dealloc;
-(id)init;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(BOOL)becomeFirstResponder;
<<<<<<< HEAD
-(void)loadView;
-(void)setSecureTextEntry:(BOOL)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
=======
-(void)setSecureTextEntry:(BOOL)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)loadView;
-(id)placeholderText;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(id)specifiers;
-(void)setTextEntryType:(int)arg1 ;
-(void)setHidesNextButton:(BOOL)arg1 ;
-(int)textEntryType;
-(Class)textEntryCellClass;
-(id)textEntryCell;
-(void)nextPressed;
<<<<<<< HEAD
-(id)textEntryView;
-(void)setTextFieldHasRoundBorder:(BOOL)arg1 ;
=======
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)updateNextButton;
-(void)setTextEntryText:(id)arg1 ;
-(id)textEntryText;
-(void)textEntryViewDidChange:(id)arg1 ;
-(void)didFinishEnteringText:(id)arg1 ;
<<<<<<< HEAD
-(void)setConvertsNumeralsToASCII:(BOOL)arg1 ;
-(unsigned)numberOfPasscodeFields;
-(void)passcodeField:(id)arg1 didUpdateEnteredPasscode:(id)arg2 ;
-(BOOL)convertsNumeralsToASCII;
-(BOOL)hidesNextButton;
-(NSString *)textValue;
=======
-(unsigned)numberOfPasscodeFields;
-(id)textEntryView;
-(void)passcodeField:(id)arg1 didUpdateEnteredPasscode:(id)arg2 ;
-(BOOL)hidesNextButton;
-(id)textValue;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)setTextValue:(NSString *)arg1 ;
-(id)textEntrySpecifier;
-(void)setTextValue:(id)arg1 forSpecifier:(id)arg2 ;
-(id)getTextValueForSpecifier:(id)arg1 ;
<<<<<<< HEAD
-(BOOL)textFieldHasRoundBorder;
=======
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(BOOL)secureTextEntry;
@end

