/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:40 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol KeychainSyncPhoneSettingsFragmentDelegate;
@class NSArray, PSPhoneNumberSpecifier, PSSpecifier, PSListController, NSString, KeychainSyncCountryInfo, PSEditableTableCell;

@interface KeychainSyncPhoneSettingsFragment : NSObject {

	NSArray* _specifiers;
	PSPhoneNumberSpecifier* _phoneNumberSpecifier;
	PSSpecifier* _countrySpecifier;
	PSListController* _listController;
	NSString* _phoneNumber;
	KeychainSyncCountryInfo* _countryInfo;
<<<<<<< HEAD
	id<KeychainSyncPhoneSettingsFragmentDelegate> _delegate;
=======
	id _delegate;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
	NSString* _title;

}

<<<<<<< HEAD
@property (nonatomic,retain,readonly) NSArray * specifiers; 
@property (nonatomic,retain) NSString * phoneNumber;                                              //@synthesize phoneNumber=_phoneNumber - In the implementation block
@property (nonatomic,retain) KeychainSyncCountryInfo * countryInfo;                               //@synthesize countryInfo=_countryInfo - In the implementation block
@property (nonatomic,retain,readonly) PSEditableTableCell * phoneNumberCell; 
@property (assign,nonatomic) id<KeychainSyncPhoneSettingsFragmentDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSString * title;                                                    //@synthesize title=_title - In the implementation block
-(void)textFieldChanged:(id)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id<KeychainSyncPhoneSettingsFragmentDelegate>)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(id<KeychainSyncPhoneSettingsFragmentDelegate>)delegate;
-(void)resignFirstResponder;
-(NSString *)title;
-(NSString *)phoneNumber;
=======
@property (nonatomic,readonly) NSArray * specifiers; 
@property (nonatomic,retain) NSString * phoneNumber;                                              //@synthesize phoneNumber=_phoneNumber - In the implementation block
@property (nonatomic,retain) KeychainSyncCountryInfo * countryInfo;                               //@synthesize countryInfo=_countryInfo - In the implementation block
@property (nonatomic,readonly) PSEditableTableCell * phoneNumberCell; 
@property (assign,nonatomic) id delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSString * title;                                                    //@synthesize title=_title - In the implementation block
-(void)setPhoneNumber:(NSString *)arg1 ;
-(void)textFieldChanged:(id)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(id)delegate;
-(void)resignFirstResponder;
-(id)title;
-(id)phoneNumber;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(id)unformattedPhoneNumber;
-(void)setDialingCountryInfo:(id)arg1 forSpecifier:(id)arg2 ;
-(id)dialingCountryInfoForSpecifier:(id)arg1 ;
-(void)setPhoneNumber:(id)arg1 forSpecifier:(id)arg2 ;
-(id)phoneNumberForSpecifier:(id)arg1 ;
<<<<<<< HEAD
-(PSEditableTableCell *)phoneNumberCell;
-(KeychainSyncCountryInfo *)countryInfo;
-(id)initWithListController:(id)arg1 ;
-(NSArray *)specifiers;
-(void)reloadSpecifiers;
-(void)setCountryInfo:(KeychainSyncCountryInfo *)arg1 ;
-(void)setPhoneNumber:(NSString *)arg1 ;
=======
-(id)phoneNumberCell;
-(id)countryInfo;
-(id)initWithListController:(id)arg1 ;
-(id)specifiers;
-(void)reloadSpecifiers;
-(void)setCountryInfo:(KeychainSyncCountryInfo *)arg1 ;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
@end

