/*
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:40 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSSetupController.h>

@class PSKeychainSyncManager;

@interface KeychainSyncSetupController : PSSetupController {

	PSKeychainSyncManager* _manager;

}
-(id)initWithManager:(id)arg1 ;
-(void)pushController:(id)arg1 ;
-(void)cancelPressed;
@end

