/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/Preferences-Structs.h>
#import <Preferences/PINView.h>
<<<<<<< HEAD
#import <Preferences/PSPasscodeFieldDelegate.h>

@class PSPasscodeField;

@interface NumericPINView : PINView <PSPasscodeFieldDelegate> {
=======

@class PSPasscodeField;

@interface NumericPINView : PINView {
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8

	PSPasscodeField* _passcodeField;

}
-(id)initWithFrame:(CGRect)arg1 ;
<<<<<<< HEAD
-(void)dealloc;
-(void)layoutSubviews;
-(BOOL)resignFirstResponder;
-(BOOL)becomeFirstResponder;
-(void)appendString:(id)arg1 ;
-(BOOL)isFirstResponder;
-(BOOL)canBecomeFirstResponder;
-(id)stringValue;
-(void)setStringValue:(id)arg1 ;
-(void)deleteLastCharacter;
-(void)passcodeField:(id)arg1 enteredPasscode:(id)arg2 ;
=======
-(void)layoutSubviews;
-(void)appendString:(id)arg1 ;
-(id)stringValue;
-(void)setStringValue:(id)arg1 ;
-(void)deleteLastCharacter;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)hidePasscodeField:(BOOL)arg1 ;
@end

