/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PINEntryView <UITextFieldDelegate>
@required
-(void)setDelegate:(id)arg1;
<<<<<<< HEAD
-(BOOL)becomeFirstResponder;
-(void)appendString:(id)arg1;
=======
-(void)appendString:(id)arg1;
-(BOOL)becomeFirstResponder;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(id)stringValue;
-(void)setStringValue:(id)arg1;
-(void)deleteLastCharacter;
-(void)setBlocked:(BOOL)arg1;
<<<<<<< HEAD
-(void)showFailedAttempts:(long)arg1;
-(void)hideFailedAttempts;
-(void)hideError;
-(void)setPINPolicyString:(id)arg1 visible:(BOOL)arg2;
-(void)setTextFieldKeyboardType:(int)arg1;
-(void)setTextFieldKeyboardAppearance:(int)arg1;
=======
-(void)showFailedAttempts:(int)arg1;
-(void)hideFailedAttempts;
-(void)hideError;
-(void)setPINPolicyString:(id)arg1 visible:(BOOL)arg2;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)showError:(id)arg1 animate:(BOOL)arg2;
-(void)setTitle:(id)arg1 font:(id)arg2;
-(void)hidePasscodeField:(BOOL)arg1;
@end

