/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:42 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSListController.h>

<<<<<<< HEAD
@class PrefsUILinkLabel, PSSpecifier, NSArray;
=======
@class PrefsUILinkLabel, PSSpecifier;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8

@interface ProblemReportingController : PSListController {

	PrefsUILinkLabel* _aboutDiagnosticsLinkLabel;
	PSSpecifier* _diagnosticDataGroupSpecifier;
<<<<<<< HEAD
	PSSpecifier* _filesystemMetadataSnapshotSpecifier;
	NSArray* _appActivitySpecifiers;
	PSSpecifier* _spinnerSpecifier;

}

@property (readonly) PSSpecifier * spinnerSpecifier; 
@property (readonly) PSSpecifier * filesystemMetadataSnapshotSpecifier; 
@property (readonly) NSArray * appActivitySpecifiers; 
+(BOOL)isProblemReportingEnabled;
-(void)dealloc;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(id)specifiers;
-(void)dismissAboutSheet:(id)arg1 ;
-(NSArray *)appActivitySpecifiers;
-(PSSpecifier *)spinnerSpecifier;
-(PSSpecifier *)filesystemMetadataSnapshotSpecifier;
-(void)snapshot:(id)arg1 ;
-(void)setShouldShareAppActivityWithAppDevelopers:(id)arg1 specifier:(id)arg2 ;
-(id)shouldShareAppActivityWithAppDevelopers;
-(void)checkDiagnosticsSessionAvailability;
-(void)launchDiagnosticsSession:(id)arg1 ;
-(BOOL)shouldEnableProblemReportingForCheckedSpecifier;
-(void)setProblemReportingEnabled:(BOOL)arg1 ;
-(void)showAboutDiagnosticsSheet;
-(void)showAboutAppAnalyticsSheet;
=======

}
+(BOOL)isProblemReportingEnabled;
-(void)dealloc;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(void)viewDidLoad;
-(id)specifiers;
-(Class)tableViewClass;
-(void)showAboutDiagnosticsSheet:(id)arg1 ;
-(void)diagnosticsDonePressed:(id)arg1 ;
-(BOOL)shouldEnableProblemReportingForCheckedSpecifier;
-(void)setProblemReportingEnabled:(BOOL)arg1 ;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
@end

