/*
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:42 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSListController.h>

@class PrefsUILinkLabel, PSSpecifier;

@interface ProblemReportingController : PSListController {

	PrefsUILinkLabel* _aboutDiagnosticsLinkLabel;
	PSSpecifier* _diagnosticDataGroupSpecifier;

}
+(BOOL)isProblemReportingEnabled;
-(void)dealloc;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(void)viewDidLoad;
-(id)specifiers;
-(Class)tableViewClass;
-(void)showAboutDiagnosticsSheet:(id)arg1 ;
-(void)diagnosticsDonePressed:(id)arg1 ;
-(BOOL)shouldEnableProblemReportingForCheckedSpecifier;
-(void)setProblemReportingEnabled:(BOOL)arg1 ;
@end

