/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:42 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@interface PSAboutTextSheetViewController : UIViewController
+(void)presentAboutSheetTitled:(id)arg1 attributedText:(id)arg2 fromViewController:(id)arg3 ;
<<<<<<< HEAD
-(void)setAttributedText:(id)arg1 ;
-(void)loadView;
-(void)donePressed;
=======
-(void)donePressed;
-(void)setAttributedText:(id)arg1 ;
-(void)loadView;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
@end

