/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class PSListController;

@interface PSBundleController : NSObject {

	PSListController* _parent;

}
-(id)bundleParentController;
-(id)bundleParentController;
-(id)bundleParentController;
-(id)bundleParentController;
-(void)load;
-(void)unload;
-(id)specifiersWithSpecifier:(id)arg1 ;
-(id)initWithParentListController:(id)arg1 ;
@end

