/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:10 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSSettingsBoolDetail.h>

@class NSString;

@interface PSCellularDataSettingsDetail : NSObject <PSSettingsBoolDetail>

@property (readonly) NSUInteger hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)setEnabled:(BOOL)arg1 ;
+(BOOL)isEnabled;
+(id)iconImage;
+(id)preferencesURL;
+(BOOL)deviceSupportsCellularData;
@end

