/*
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PSController <NSObject>
@required
-(id)specifier;
-(void)setSpecifier:(id)arg1;
-(void)suspend;
-(void)handleURL:(id)arg1;
-(id)parentController;
-(void)setParentController:(id)arg1;
-(id)rootController;
-(void)setRootController:(id)arg1;
-(void)pushController:(id)arg1;
-(BOOL)canBeShownFromSuspendedState;
-(void)setPreferenceValue:(id)arg1 specifier:(id)arg2;
-(id)readPreferenceValue:(id)arg1;
-(void)didLock;
-(void)willUnlock;
-(void)didUnlock;
-(void)didWake;
-(void)willResignActive;
-(void)willBecomeActive;
-(void)statusBarWillAnimateByHeight:(float)arg1;
@end

