/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


<<<<<<< HEAD
@protocol PSController
@optional
+(void)validateSpecifier:(id)arg1;
+(void)formatSearchEntries:(id)arg1 parent:(id)arg2;
+(id)searchBundle;
-(void)highlightSpecifierWithID:(id)arg1;
-(BOOL)prepareHandlingURLForSpecifierID:(id)arg1 resourceDictionary:(id)arg2 animatePush:(BOOL*)arg3;
-(void)pushController:(id)arg1;
-(void)pushController:(id)arg1 animate:(BOOL)arg2;

=======
@protocol PSController <NSObject>
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
@required
-(id)specifier;
-(void)setSpecifier:(id)arg1;
-(void)suspend;
<<<<<<< HEAD
=======
-(void)handleURL:(id)arg1;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(id)parentController;
-(void)setParentController:(id)arg1;
-(id)rootController;
-(void)setRootController:(id)arg1;
<<<<<<< HEAD
-(void)showController:(id)arg1;
-(void)showController:(id)arg1 animate:(BOOL)arg2;
-(void)handleURL:(id)arg1;
=======
-(void)pushController:(id)arg1;
-(BOOL)canBeShownFromSuspendedState;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)setPreferenceValue:(id)arg1 specifier:(id)arg2;
-(id)readPreferenceValue:(id)arg1;
-(void)didLock;
-(void)willUnlock;
-(void)didUnlock;
-(void)didWake;
-(void)willResignActive;
-(void)willBecomeActive;
-(void)statusBarWillAnimateByHeight:(float)arg1;
@end

