/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:42 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSTableCell.h>

@class UIControl;

@interface PSControlTableCell : PSTableCell {

	UIControl* _control;

}

@property (nonatomic,retain) UIControl * control; 
<<<<<<< HEAD
=======
-(void)setControl:(UIControl *)arg1 ;
-(id)valueLabel;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)dealloc;
-(BOOL)canReload;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3 ;
-(void)refreshCellContentsWithSpecifier:(id)arg1 ;
-(id)newControl;
-(void)controlChanged:(id)arg1 ;
-(id)controlValue;
<<<<<<< HEAD
-(id)valueLabel;
-(void)setControl:(UIControl *)arg1 ;
-(UIControl *)control;
=======
-(id)control;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
@end

