/*
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/Preferences-Structs.h>

@class UIColor;

@interface PSDiscreteSlider : UISlider {

	UIColor* _trackMarkersColor;

}

@property (nonatomic,retain) UIColor * trackMarkersColor;              //@synthesize trackMarkersColor=_trackMarkersColor - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)drawRect:(CGRect)arg1 ;
-(CGRect)trackRectForBounds:(CGRect)arg1 ;
-(CGRect)thumbRectForBounds:(CGRect)arg1 trackRect:(CGRect)arg2 value:(float)arg3 ;
-(void)setValue:(float)arg1 animated:(BOOL)arg2 ;
-(void)sliderTapped:(id)arg1 ;
-(void)setTrackMarkersColor:(UIColor *)arg1 ;
-(id)trackMarkersColor;
@end

