/*
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:42 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSSettingsBoolDetail.h>

@interface PSDNDSettingsDetail : NSObject <PSSettingsBoolDetail>
+(BOOL)isEnabled;
+(void)setEnabled:(BOOL)arg1 ;
+(id)iconImage;
+(id)preferencesURL;
+(void)loadStateWithCompletion:(/*^block*/ id)arg1 ;
@end

