/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:10 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:43 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

<<<<<<< HEAD
#import <Preferences/PSSpecifierGroupController.h>

@class PSListController, PSSpecifier, NSMutableArray, NSString;

@interface PSExpandableListGroupController : NSObject <PSSpecifierGroupController> {
=======

@class PSListController, PSSpecifier, NSMutableArray, NSArray;

@interface PSExpandableListGroupController : NSObject {
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8

	PSListController* _listController;
	PSSpecifier* _groupSpecifier;
	int _collaspeAfterCount;
	NSMutableArray* _specifiers;
	BOOL _showAll;
	PSSpecifier* _showAllSpecifier;
	PSSpecifier* _spinnerSpecifier;

}

<<<<<<< HEAD
@property (readonly) NSUInteger hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
-(void)reloadSpecifier:(id)arg1 ;
-(id)specifiers;
-(int)_groupIndex;
-(id)spinnerSpecifier;
-(id)initWithListController:(id)arg1 groupSpecifier:(id)arg2 collapseAfterCount:(int)arg3 ;
-(id)showAllSpecifier;
=======
@property (readonly) NSArray * specifiers; 
-(void)dealloc;
-(void)reloadSpecifier:(id)arg1 ;
-(id)specifiers;
-(id)initWithListController:(id)arg1 groupSpecifier:(id)arg2 collapseAfterCount:(int)arg3 ;
-(int)_groupIndex;
-(id)showAllSpecifier;
-(id)spinnerSpecifier;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)showAll;
-(id)initWithListController:(id)arg1 groupSpecifier:(id)arg2 ;
-(void)addSpecifiers:(id)arg1 ;
-(void)removeAllSpecifiers;
@end

