/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PSHeaderFooterView
@optional
-(float)preferredHeightForWidth:(float)arg1 inTableView:(id)arg2;
-(float)preferredHeightForWidth:(float)arg1;

@required
-(id)initWithSpecifier:(id)arg1;
@end

