/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSSetupController.h>

<<<<<<< HEAD
@class NSString, PSLanguageSelector;

@interface PSInternationalLanguageSetupController : PSSetupController <UIActionSheetDelegate, UIAlertViewDelegate> {

	NSString* _languageToSet;
	BOOL _notOfficialLanguage;
	BOOL _useOfficialLanguages;
	PSLanguageSelector* _languageSelector;

}

@property (nonatomic,retain) PSLanguageSelector * languageSelector;              //@synthesize languageSelector=_languageSelector - In the implementation block
@property (readonly) NSUInteger hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
-(id)init;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(void)commit;
-(BOOL)disablesAutomaticKeyboardDismissal;
-(void)setupController;
-(void)setLanguageSelector:(PSLanguageSelector *)arg1 ;
-(BOOL)useOfficialLanguages;
-(PSLanguageSelector *)languageSelector;
-(void)setNotOfficialLanguage:(BOOL)arg1 ;
-(void)setLanguage:(id)arg1 specifier:(id)arg2 ;
-(void)didFinishCommit;
-(void)saveLanguage:(BOOL)arg1 ;
-(void)changeLanguageWithIndex:(unsigned)arg1 tag:(unsigned)arg2 ;
-(void)showBlackViewWithLabel:(id)arg1 moveLanguageToTop:(BOOL)arg2 withLanguageIdentifier:(id)arg3 ;
-(id)initWithOfficialLanguages;
=======
@class NSString;

@interface PSInternationalLanguageSetupController : PSSetupController {

	NSString* _languageToSet;

}
-(void)dealloc;
-(void)commit;
-(void)setupController;
-(void)rotateView:(id)arg1 toOrientation:(int)arg2 ;
-(void)didFinishCommit;
-(void)showBlackViewWithLabel:(id)arg1 ;
-(void)setLanguage:(id)arg1 specifier:(id)arg2 ;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(id)language:(id)arg1 ;
@end

