/*
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSListItemsController.h>

@class NSMutableDictionary;

@interface PSInternationalLanguageController : PSListItemsController {

	NSMutableDictionary* _cellCache;

}

@property (nonatomic,retain) NSMutableDictionary * cellCache;              //@synthesize cellCache=_cellCache - In the implementation block
-(void)dealloc;
-(id)init;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(id)specifiers;
-(void)cancelButtonTapped;
-(void)_removeBlackFrame;
-(void)setCellCache:(NSMutableDictionary *)arg1 ;
-(void)doneButtonTapped;
-(void)updateNavigationItem;
-(id)cellCache;
-(void)generateLanguageCellCache;
@end

