/*
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSSetupController.h>

@class NSString;

@interface PSInternationalLanguageSetupController : PSSetupController {

	NSString* _languageToSet;

}
-(void)dealloc;
-(void)commit;
-(void)setupController;
-(void)rotateView:(id)arg1 toOrientation:(int)arg2 ;
-(void)didFinishCommit;
-(void)showBlackViewWithLabel:(id)arg1 ;
-(void)setLanguage:(id)arg1 specifier:(id)arg2 ;
-(id)language:(id)arg1 ;
@end

