/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSListController.h>

<<<<<<< HEAD
@class UILabel, NSArray, PSSpecifier;
=======
@class UILabel, NSArray;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8

@interface PSLargeTextController : PSListController {

	UILabel* _bodyExampleLabel;
	UILabel* _headlineExampleLabel;
	int _selectedCategoryIndex;
	NSArray* _contentSizeCategories;
<<<<<<< HEAD
	PSSpecifier* _sliderGroupSpecifier;
=======
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
	BOOL _usesExtendedRange;
	BOOL _showsExtendedRangeSwitch;

}

@property (assign,nonatomic) BOOL showsExtendedRangeSwitch;              //@synthesize showsExtendedRangeSwitch=_showsExtendedRangeSwitch - In the implementation block
-(void)dealloc;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2 ;
<<<<<<< HEAD
=======
-(int)numberOfSectionsInTableView:(id)arg1 ;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)viewDidLayoutSubviews;
-(void)loadView;
-(id)specifiers;
-(void)sizeCategoryDidChange:(id)arg1 ;
<<<<<<< HEAD
=======
-(void)updateExampleFonts;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)setUsesExtendedRange:(id)arg1 forSpecifier:(id)arg2 ;
-(id)usesExtendedRangeForSpecifier:(id)arg1 ;
-(void)setDynamicTypeValue:(id)arg1 forSpecifier:(id)arg2 ;
-(id)getDynamicTypeValueForSpecifier:(id)arg1 ;
<<<<<<< HEAD
-(void)setShowsExtendedRangeSwitch:(BOOL)arg1 ;
-(BOOL)showsExtendedRangeSwitch;
=======
-(BOOL)showsExtendedRangeSwitch;
-(void)setShowsExtendedRangeSwitch:(BOOL)arg1 ;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
@end

