/*
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSListController.h>

@class PSSpecifier;

@interface PSLocaleController : PSListController {

	PSSpecifier* _checkedSpecifier;
	BOOL _firstAppearance;

}
-(void)dealloc;
-(id)init;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(id)specifiers;
-(void)setLocale:(id)arg1 specifier:(id)arg2 ;
-(void)updateChecked:(id)arg1 ;
-(void)addLanguage:(id)arg1 toSupportedLanguages:(id)arg2 ;
-(void)subcategorySelected:(id)arg1 specifier:(id)arg2 ;
-(id)locale:(id)arg1 ;
-(void)localeChangedAction;
@end

