/*
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@protocol PSPasscodeFieldDelegate;
@class NSMutableArray, NSMutableString;

@interface PSPasscodeField : UIView <UIKeyInput> {

	NSMutableArray* _dashViews;
	NSMutableArray* _dotViews;
	NSMutableArray* _digitViews;
	NSMutableString* _stringValue;
	BOOL _securePasscodeEntry;
	id _delegate;
	unsigned _numberOfEntryFields;

}

@property (assign,nonatomic) id delegate;                       //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) unsigned numberOfEntryFields;                             //@synthesize numberOfEntryFields=_numberOfEntryFields - In the implementation block
@property (assign,nonatomic) BOOL securePasscodeEntry;                                   //@synthesize securePasscodeEntry=_securePasscodeEntry - In the implementation block
@property (assign,nonatomic) int autocapitalizationType; 
@property (assign,nonatomic) int autocorrectionType; 
@property (assign,nonatomic) int spellCheckingType; 
@property (assign,nonatomic) int keyboardType; 
@property (assign,nonatomic) int keyboardAppearance; 
@property (assign,nonatomic) int returnKeyType; 
@property (assign,nonatomic) BOOL enablesReturnKeyAutomatically; 
@property (assign,getter=isSecureTextEntry,nonatomic) BOOL secureTextEntry; 
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(void)layoutSubviews;
-(id)delegate;
-(BOOL)becomeFirstResponder;
-(BOOL)canBecomeFirstResponder;
-(BOOL)hasText;
-(void)insertText:(id)arg1 ;
-(void)deleteBackward;
-(void)setSecureTextEntry:(BOOL)arg1 ;
-(BOOL)isSecureTextEntry;
-(int)keyboardType;
-(id)stringValue;
-(void)setStringValue:(id)arg1 ;
-(unsigned)numberOfEntryFields;
-(BOOL)securePasscodeEntry;
-(void)setSecurePasscodeEntry:(BOOL)arg1 ;
-(id)initWithNumberOfEntryFields:(unsigned)arg1 ;
@end

