/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSRootController.h>

@protocol PSController;
@class NSDictionary, UIViewController, PSRootController;

@interface PSSetupController : PSRootController {

	NSDictionary* _rootInfo;
<<<<<<< HEAD
	UIViewController* _parentController;
=======
	UIViewController<PSController>* _parentController;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
	PSRootController* _parentRootController;

}
-(void)dealloc;
-(id)init;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)dismiss;
<<<<<<< HEAD
-(void)dismissAnimated:(BOOL)arg1 ;
-(id)controller;
-(id)parentController;
-(void)setParentController:(id)arg1 ;
-(void)setupController;
-(void)dismissWithCompletion:(/*^block*/ id)arg1 ;
-(BOOL)usePopupStyle;
-(BOOL)popupStyleIsModal;
-(void)showController:(id)arg1 animate:(BOOL)arg2 ;
-(void)handleURL:(id)arg1 ;
-(void)statusBarWillChangeHeight:(id)arg1 ;
-(void)dismissAnimated:(BOOL)arg1 completion:(/*^block*/ id)arg2 ;
=======
-(id)controller;
-(void)dismissAnimated:(BOOL)arg1 ;
-(void)handleURL:(id)arg1 ;
-(id)parentController;
-(void)setParentController:(id)arg1 ;
-(void)setupController;
-(void)pushController:(id)arg1 ;
-(BOOL)usePopupStyle;
-(BOOL)popupStyleIsModal;
-(void)statusBarWillChangeHeight:(id)arg1 ;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)pushControllerOnParentWithSpecifier:(id)arg1 ;
-(void)popControllerOnParent;
@end

