/*
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSRootController.h>

@protocol PSController;
@class NSDictionary, UIViewController, PSRootController;

@interface PSSetupController : PSRootController {

	NSDictionary* _rootInfo;
	UIViewController<PSController>* _parentController;
	PSRootController* _parentRootController;

}
-(void)dealloc;
-(id)init;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)dismiss;
-(id)controller;
-(void)dismissAnimated:(BOOL)arg1 ;
-(void)handleURL:(id)arg1 ;
-(id)parentController;
-(void)setParentController:(id)arg1 ;
-(void)setupController;
-(void)pushController:(id)arg1 ;
-(BOOL)usePopupStyle;
-(BOOL)popupStyleIsModal;
-(void)statusBarWillChangeHeight:(id)arg1 ;
-(void)pushControllerOnParentWithSpecifier:(id)arg1 ;
-(void)popControllerOnParent;
@end

