/*
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <Preferences/Preferences-Structs.h>
@interface PSSystemConfigurationDynamicStoreMISWatcher : NSObject {

	CFRunLoopSourceRef _scRunLoopSource;
	SCDynamicStoreRef _scDynamicStore;
	int _misState;
	int _misReason;

}
+(id)sharedManager;
-(void)dealloc;
-(id)init;
-(void)readMISState:(int*)arg1 andReason:(int*)arg2 ;
-(void)getMISState:(int*)arg1 andReason:(int*)arg2 ;
-(void)sendStateUpdate;
@end

