/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

<<<<<<< HEAD
@class UIImageView, NSString, PSSpecifier, PSTableCellHighlightContext, UILongPressGestureRecognizer;
=======
@class UIImageView, NSString, PSSpecifier, UILongPressGestureRecognizer;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8

@interface PSTableCell : UITableViewCell {

	id _value;
	UIImageView* _checkedImageView;
	BOOL _checked;
	BOOL _shouldHideTitle;
	NSString* _hiddenTitle;
	int _alignment;
	SEL _pAction;
	id _pTarget;
	BOOL _cellEnabled;
	PSSpecifier* _specifier;
	int _type;
	BOOL _lazyIcon;
	BOOL _lazyIconDontUnload;
	BOOL _lazyIconForceSynchronous;
	NSString* _lazyIconAppID;
	BOOL _reusedCell;
<<<<<<< HEAD
	PSTableCellHighlightContext* _customHighlightContext;
	BOOL _forceHideDisclosureIndicator;
=======
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
	BOOL _isCopyable;
	UILongPressGestureRecognizer* _longTapRecognizer;

}

@property (assign,nonatomic) int type;                                                      //@synthesize type=_type - In the implementation block
@property (nonatomic,retain) PSSpecifier * specifier;                                       //@synthesize specifier=_specifier - In the implementation block
@property (assign,nonatomic) BOOL reusedCell;                                               //@synthesize reusedCell=_reusedCell - In the implementation block
<<<<<<< HEAD
@property (assign,nonatomic) BOOL forceHideDisclosureIndicator;                             //@synthesize forceHideDisclosureIndicator=_forceHideDisclosureIndicator - In the implementation block
@property (assign,nonatomic) BOOL isCopyable;                                               //@synthesize isCopyable=_isCopyable - In the implementation block
@property (nonatomic,retain) UILongPressGestureRecognizer * longTapRecognizer;              //@synthesize longTapRecognizer=_longTapRecognizer - In the implementation block
+(float)defaultCellHeight;
=======
@property (assign,nonatomic) BOOL isCopyable;                                               //@synthesize isCopyable=_isCopyable - In the implementation block
@property (nonatomic,retain) UILongPressGestureRecognizer * longTapRecognizer;              //@synthesize longTapRecognizer=_longTapRecognizer - In the implementation block
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
+(int)cellStyle;
+(id)reuseIdentifierForSpecifier:(id)arg1 ;
+(Class)cellClassForSpecifier:(id)arg1 ;
+(id)stringFromCellType:(int)arg1 ;
+(id)reuseIdentifierForClassAndType:(int)arg1 ;
+(id)reuseIdentifierForBasicCellTypes:(int)arg1 ;
+(int)cellTypeFromString:(id)arg1 ;
<<<<<<< HEAD
-(PSSpecifier *)specifier;
-(void)setSpecifier:(PSSpecifier *)arg1 ;
-(id)iconImageView;
-(void)setAlignment:(int)arg1 ;
=======
-(id)specifier;
-(void)setSpecifier:(PSSpecifier *)arg1 ;
-(id)valueLabel;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)dealloc;
-(void)layoutSubviews;
-(void)setChecked:(BOOL)arg1 ;
-(void)setTitle:(id)arg1 ;
-(BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2 ;
-(void)setTarget:(id)arg1 ;
-(void)setType:(int)arg1 ;
-(int)type;
-(SEL)action;
<<<<<<< HEAD
-(id)title;
-(void)setValue:(id)arg1 ;
-(id)_automationID;
-(id)target;
-(id)scriptingInfoWithChildren;
-(id)value;
-(BOOL)canBecomeFirstResponder;
-(id)titleLabel;
-(void)setAction:(SEL)arg1 ;
=======
-(void)setValue:(id)arg1 ;
-(id)_automationID;
-(void)setAlignment:(int)arg1 ;
-(id)scriptingInfoWithChildren;
-(id)value;
-(BOOL)canBecomeFirstResponder;
-(id)target;
-(id)title;
-(id)titleLabel;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)prepareForReuse;
-(id)_contentString;
<<<<<<< HEAD
=======
-(void)setAction:(SEL)arg1 ;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)copy:(id)arg1 ;
-(void)setIcon:(id)arg1 ;
-(float)textFieldOffset;
-(BOOL)isChecked;
<<<<<<< HEAD
=======
-(id)iconImageView;
-(void)setCellEnabled:(BOOL)arg1 ;
-(BOOL)cellEnabled;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(BOOL)canReload;
-(void)reloadWithSpecifier:(id)arg1 animated:(BOOL)arg2 ;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3 ;
-(void)setReusedCell:(BOOL)arg1 ;
-(void)refreshCellContentsWithSpecifier:(id)arg1 ;
-(void)forceSynchronousIconLoadOnNextIconLoad;
-(void)cellRemovedFromView;
-(BOOL)canBeChecked;
<<<<<<< HEAD
-(void)highlightCellForDuration:(double)arg1 animateUnighlight:(BOOL)arg2 ;
-(void)_invalidateHighlightContext;
-(id)_copyableText;
-(void)_updateAccessoryTypeForSpecifier:(id)arg1 ;
=======
-(id)_copyableText;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)longPressed:(id)arg1 ;
-(void)setShouldHideTitle:(BOOL)arg1 ;
-(id)blankIcon;
-(id)getLazyIcon;
-(id)getLazyIconID;
<<<<<<< HEAD
-(void)setCellEnabled:(BOOL)arg1 ;
=======
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)setValueChangedTarget:(id)arg1 action:(SEL)arg2 specifier:(id)arg3 ;
-(void)setCellTarget:(id)arg1 ;
-(void)setCellAction:(SEL)arg1 ;
-(id)cellTarget;
-(SEL)cellAction;
<<<<<<< HEAD
-(void)setForceHideDisclosureIndicator:(BOOL)arg1 ;
-(id)titleTextLabel;
-(id)getIcon;
-(BOOL)cellEnabled;
-(BOOL)reusedCell;
-(BOOL)forceHideDisclosureIndicator;
-(BOOL)isCopyable;
-(void)setIsCopyable:(BOOL)arg1 ;
-(UILongPressGestureRecognizer *)longTapRecognizer;
-(void)setLongTapRecognizer:(UILongPressGestureRecognizer *)arg1 ;
-(id)valueLabel;
=======
-(id)titleTextLabel;
-(id)getIcon;
-(BOOL)reusedCell;
-(BOOL)isCopyable;
-(void)setIsCopyable:(BOOL)arg1 ;
-(id)longTapRecognizer;
-(void)setLongTapRecognizer:(UILongPressGestureRecognizer *)arg1 ;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
@end

