/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSTimer, UITableViewCell;

@interface PSTableCellHighlightContext : NSObject {

	NSTimer* _timer;
	BOOL _animateUnhighlight;
	BOOL _valid;
	UITableViewCell* _cell;
	int _originalSelectionStyle;

}

@property (assign,nonatomic) UITableViewCell * cell;                  //@synthesize cell=_cell - In the implementation block
@property (nonatomic,readonly) BOOL animateUnhighlight;               //@synthesize animateUnhighlight=_animateUnhighlight - In the implementation block
@property (assign,nonatomic) int originalSelectionStyle;              //@synthesize originalSelectionStyle=_originalSelectionStyle - In the implementation block
@property (nonatomic,readonly) BOOL valid;                            //@synthesize valid=_valid - In the implementation block
+(id)contextWithCell:(id)arg1 ;
-(void)_killTimer;
-(void)_timerFired;
-(void)dealloc;
-(void)invalidate;
-(UITableViewCell *)cell;
-(BOOL)valid;
-(void)setCell:(UITableViewCell *)arg1 ;
-(void)performHighlightForDuration:(double)arg1 animateUnhighlight:(BOOL)arg2 ;
-(BOOL)animateUnhighlight;
-(int)originalSelectionStyle;
-(void)setOriginalSelectionStyle:(int)arg1 ;
@end

