/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PSViewControllerOffsetProtocol
@required
-(void)setDesiredVerticalContentOffset:(float)arg1;
-(void)setDesiredVerticalContentOffsetItemNamed:(id)arg1;
-(float)verticalContentOffset;
@end

