/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:41 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>
#import <Preferences/PSHeaderFooterView.h>

@class UILabel;

@interface RegionFormatSampleView : UIView <PSHeaderFooterView> {

	UILabel* _labels[4];
	float _sized;
	float _labelTopPadding[4];

}
-(id)initWithSpecifier:(id)arg1 ;
<<<<<<< HEAD
-(void)dealloc;
-(void)layoutSubviews;
-(float)preferredHeightForWidth:(float)arg1 ;
=======
-(float)preferredHeightForWidth:(float)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)setTextForRegionExample:(id)arg1 ;
-(id)generateRegionSampleLabel;
-(id)_accessibilityLabels;
@end

