/*
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:40 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UIActionSheetDelegate <NSObject>
@optional
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)actionSheetCancel:(id)arg1;
-(void)willPresentActionSheet:(id)arg1;
-(void)didPresentActionSheet:(id)arg1;
-(void)actionSheet:(id)arg1 willDismissWithButtonIndex:(int)arg2;
-(void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
@end

