/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:40 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UIAlertViewDelegate <NSObject>
@optional
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
-(void)alertViewCancel:(id)arg1;
<<<<<<< HEAD
-(void)willPresentAlertView:(id)arg1;
-(BOOL)alertViewShouldEnableFirstOtherButton:(id)arg1;
-(void)didPresentAlertView:(id)arg1;
=======
-(BOOL)alertViewShouldEnableFirstOtherButton:(id)arg1;
-(void)didPresentAlertView:(id)arg1;
-(void)willPresentAlertView:(id)arg1;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)alertView:(id)arg1 willDismissWithButtonIndex:(int)arg2;
@end

