/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UIAlertViewDelegate <NSObject>
@optional
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
-(void)alertViewCancel:(id)arg1;
-(void)willPresentAlertView:(id)arg1;
-(BOOL)alertViewShouldEnableFirstOtherButton:(id)arg1;
-(void)didPresentAlertView:(id)arg1;
-(void)alertView:(id)arg1 willDismissWithButtonIndex:(int)arg2;
@end

