/*
<<<<<<< HEAD
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:10 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
=======
* This header is generated by classdump-dyld 0.2
* on Wednesday, May 21, 2014 at 1:42:42 PM Central European Summer Time
* Operating System: Version 7.0.6 (Build 11B651)
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UITextContentViewDelegate <NSObject>
@optional
<<<<<<< HEAD
=======
-(void)textContentViewDidBeginEditing:(id)arg1;
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
-(void)textContentViewDidEndEditing:(id)arg1;
-(BOOL)textContentViewShouldBeginEditing:(id)arg1;
-(BOOL)textContentViewShouldEndEditing:(id)arg1;
-(BOOL)textContentView:(id)arg1 shouldScrollForPendingContentSize:(CGSize)arg2;
-(BOOL)textContentView:(id)arg1 shouldChangeSizeForContentSize:(CGSize)arg2;
-(void)textContentView:(id)arg1 didChangeSize:(CGSize)arg2;
-(BOOL)textContentView:(id)arg1 shouldChangeTextInRange:(NSRange)arg2 replacementText:(id)arg3;
-(void)textContentViewDidChange:(id)arg1;
-(void)textContentViewDidChangeSelection:(id)arg1;
<<<<<<< HEAD
-(void)textContentViewDidBeginEditing:(id)arg1;
=======
>>>>>>> 9b3c8b97620825ae25bfcb8647c947dfc8814ae8
@end

