/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UITextInputTraits <NSObject>
@property (assign,nonatomic) UITextAutocapitalizationType autocapitalizationType; 
@property (assign,nonatomic) UITextAutocorrectionType autocorrectionType; 
@property (assign,nonatomic) UITextSpellCheckingType spellCheckingType; 
@property (assign,nonatomic) UIKeyboardType keyboardType; 
@property (assign,nonatomic) UIKeyboardAppearance keyboardAppearance; 
@property (assign,nonatomic) UIReturnKeyType returnKeyType; 
@property (assign,nonatomic) BOOL enablesReturnKeyAutomatically; 
@property (assign,getter=isSecureTextEntry,nonatomic) BOOL secureTextEntry; 
@optional
-(UIKeyboardAppearance)keyboardAppearance;
-(void)setSecureTextEntry:(BOOL)arg1;
-(BOOL)isSecureTextEntry;
-(UITextAutocapitalizationType)autocapitalizationType;
-(void)setAutocapitalizationType:(UITextAutocapitalizationType)arg1;
-(UITextAutocorrectionType)autocorrectionType;
-(void)setAutocorrectionType:(UITextAutocorrectionType)arg1;
-(int)spellCheckingType;
-(void)setSpellCheckingType:(int)arg1;
-(UIKeyboardType)keyboardType;
-(void)setKeyboardType:(UIKeyboardType)arg1;
-(void)setKeyboardAppearance:(UIKeyboardAppearance)arg1;
-(int)returnKeyType;
-(void)setReturnKeyType:(int)arg1;
-(BOOL)enablesReturnKeyAutomatically;
-(void)setEnablesReturnKeyAutomatically:(BOOL)arg1;
@end

