/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:54:28 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/XPCServices/com.apple.Preferences.FilesystemMetadataSnapshotService.xpc/com.apple.Preferences.FilesystemMetadataSnapshotService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <com.apple.Preferences.FilesystemMetadataSnapshotService/NSXPCListenerDelegate.h>

@class NSString;

@interface ServiceDelegate : NSObject <NSXPCListenerDelegate>

@property (readonly) NSUInteger hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2 ;
@end

