/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:54:28 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/XPCServices/com.apple.Preferences.FilesystemMetadataSnapshotService.xpc/com.apple.Preferences.FilesystemMetadataSnapshotService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol NSXPCListenerDelegate <NSObject>
@optional
-(BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
@end

