/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:54:28 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/XPCServices/com.apple.Preferences.FilesystemMetadataSnapshotService.xpc/com.apple.Preferences.FilesystemMetadataSnapshotService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <com.apple.Preferences.FilesystemMetadataSnapshotService/com.apple.Preferences.FilesystemMetadataSnapshotService-Structs.h>
@interface PSFilesystemMetadataSnapshotArchiver : NSObject
+(BOOL)compressSnapshotWithName:(id)arg1 atPath:(id)arg2 withLogFile:(_sFILE*)arg3 ;
@end

