/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:10 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol KeychainSyncPasscodeFieldDelegate <NSObject>
@required
-(void)passcodeField:(id)arg1 didUpdateEnteredPasscode:(id)arg2;
@end

