/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface PSBiometricIdentity : NSObject
+(void)removeIdentity:(id)arg1 ;
+(id)identities;
+(id)nameForIdentity:(id)arg1 ;
+(int)maximumIdentityCount;
+(void)setName:(id)arg1 forIdentity:(id)arg2 ;
+(id)nextIdentityName;
@end

