/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:10 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/Preferences-Structs.h>
#import <Preferences/PSListController.h>

@protocol OS_dispatch_semaphore, PSMagnifyControllerDelegate;
@class PSMagnifyMode, UISegmentedControl, UIScrollView, UIPageControl, UIView, NSURL, NSMutableDictionary, NSObject, NSString;

@interface PSMagnifyController : PSListController <UIScrollViewDelegate, UIWebViewDelegate> {

	PSMagnifyMode* _originalMagnifyMode;
	PSMagnifyMode* _selectedMagnifyMode;
	UISegmentedControl* _magnifyModePicker;
	UIScrollView* _previewsScroller;
	UIPageControl* _pageControl;
	UIView* _dividerLine;
	NSURL* _HTMLResourceBaseURL;
	NSMutableDictionary* _webViewsForMagnifyMode;
	BOOL _loaded;
	PSMagnifyMode* _initialMagnifyMode;
	BOOL _doneButtonCommits;
	id<PSMagnifyControllerDelegate> _delegate;

}

@property (assign,nonatomic) BOOL doneButtonCommits;                                //@synthesize doneButtonCommits=_doneButtonCommits - In the implementation block
@property (assign,nonatomic) id<PSMagnifyControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) NSUInteger hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)commitMagnifyMode:(id)arg1 withRelaunchURL:(id)arg2 ;
+(BOOL)shouldShowMagnify;
+(id)localizedMagnifyModeName;
+(id)currentMagnifyMode;
+(void)commitMagnifyMode:(id)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id<PSMagnifyControllerDelegate>)arg1 ;
-(id)init;
-(void)scrollViewDidScroll:(id)arg1 ;
-(id<PSMagnifyControllerDelegate>)delegate;
-(void)viewDidLayoutSubviews;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)loadView;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)webViewDidFinishLoad:(id)arg1 ;
-(void)updateNavigationButtons;
-(id)specifiers;
-(id)initWithZoomedSelected:(BOOL)arg1 ;
-(id)arrayOfWebViewsWithCount:(unsigned)arg1 ;
-(id)localizedCSSStringFromUnlocalizedCSSString:(id)arg1 ;
-(void)magnifyModeSelectionChanged:(id)arg1 ;
-(void)setSelectedMagnifyMode:(id)arg1 ;
-(id)currentWebViewSet;
-(BOOL)doneButtonCommits;
-(void)magnifyModeConfirmed:(id)arg1 ;
-(void)finishDone:(id)arg1 ;
-(void)finishCancel:(id)arg1 ;
-(void)setDoneButtonCommits:(BOOL)arg1 ;
@end

