/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@protocol PSPasscodeFieldDelegate;
@class NSMutableArray, NSMutableString, NSString;

@interface PSPasscodeField : UIView <UIKeyInput> {

	NSMutableArray* _dashViews;
	NSMutableArray* _dotViews;
	NSMutableArray* _digitViews;
	NSMutableString* _stringValue;
	BOOL _securePasscodeEntry;
	id<PSPasscodeFieldDelegate> _delegate;
	unsigned _numberOfEntryFields;

}

@property (assign,nonatomic) id<PSPasscodeFieldDelegate> delegate;                       //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) unsigned numberOfEntryFields;                             //@synthesize numberOfEntryFields=_numberOfEntryFields - In the implementation block
@property (assign,nonatomic) BOOL securePasscodeEntry;                                   //@synthesize securePasscodeEntry=_securePasscodeEntry - In the implementation block
@property (readonly) NSUInteger hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) UITextAutocapitalizationType autocapitalizationType; 
@property (assign,nonatomic) UITextAutocorrectionType autocorrectionType; 
@property (assign,nonatomic) UITextSpellCheckingType spellCheckingType; 
@property (assign,nonatomic) UIKeyboardType keyboardType; 
@property (assign,nonatomic) UIKeyboardAppearance keyboardAppearance; 
@property (assign,nonatomic) UIReturnKeyType returnKeyType; 
@property (assign,nonatomic) BOOL enablesReturnKeyAutomatically; 
@property (assign,getter=isSecureTextEntry,nonatomic) BOOL secureTextEntry; 
-(void)dealloc;
-(void)setDelegate:(id<PSPasscodeFieldDelegate>)arg1 ;
-(void)layoutSubviews;
-(id<PSPasscodeFieldDelegate>)delegate;
-(BOOL)becomeFirstResponder;
-(BOOL)canBecomeFirstResponder;
-(BOOL)hasText;
-(void)insertText:(id)arg1 ;
-(void)deleteBackward;
-(void)setSecureTextEntry:(BOOL)arg1 ;
-(BOOL)isSecureTextEntry;
-(UIKeyboardType)keyboardType;
-(id)stringValue;
-(void)setStringValue:(id)arg1 ;
-(unsigned)numberOfEntryFields;
-(BOOL)securePasscodeEntry;
-(void)setSecurePasscodeEntry:(BOOL)arg1 ;
-(id)initWithNumberOfEntryFields:(unsigned)arg1 ;
@end

