/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:10 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/Preferences-Structs.h>
#import <Preferences/NSCopying.h>

@class NSMutableArray, NSArray;

@interface PSSpecifierGroupIndex : NSObject <NSCopying> {

	NSMutableArray* _specifiers;
	NSMutableArray* _groupSections;
	NSMutableArray* _groupSpecifiers;
	NSMutableArray* _ungroupedPrefixSpecifiers;
	BOOL _wantsDebugCallbacks;

}

@property (nonatomic,copy,readonly) NSArray * specifiers;                   //@synthesize specifiers=_specifiers - In the implementation block
@property (nonatomic,copy,readonly) NSArray * groupSpecifiers; 
+(BOOL)_wantsDebuggingCallbacks;
+(id)groupIndexWithSpecifiers:(id)arg1 ;
-(unsigned)indexOfGroup:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(id)description;
-(id)_init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSArray *)specifiers;
-(BOOL)getGroup:(out unsigned*)arg1 row:(out unsigned*)arg2 ofSpecifierAtIndex:(unsigned)arg3 ;
-(id)specifiersInGroup:(id)arg1 ;
-(BOOL)getGroup:(out unsigned*)arg1 row:(out unsigned*)arg2 ofSpecifier:(id)arg3 ;
-(id)indexPathForSpecifier:(id)arg1 ;
-(void)performSpecifierUpdates:(id)arg1 ;
-(unsigned)numberOfGroups;
-(id)initWithSpecifiers:(id)arg1 ;
-(void)performUpdateOperation:(id)arg1 ;
-(unsigned)indexOfSpecifierAtIndexPath:(id)arg1 forInsertion:(BOOL)arg2 ;
-(NSRange)rangeOfSpecifiersInGroupAtGroupIndex:(unsigned)arg1 ;
-(NSArray *)groupSpecifiers;
-(unsigned)indexOfSpecifierAtIndexPath:(id)arg1 ;
-(unsigned)groupIndexOfGroup:(id)arg1 ;
-(unsigned)groupIndexOfGroupWithID:(id)arg1 ;
-(void)performSpecifierUpdatesUsingBlock:(/*^block*/ id)arg1 ;
-(void)_createGroupIndex;
-(id)_initForCopyWithGroupIndex:(id)arg1 ;
-(id)_ungroupedPrefixSpecifiers;
-(void)reloadWithSpecifiers:(id)arg1 ;
-(void)performUpdateOperation:(id)arg1 forSpecifierUpdates:(id)arg2 ;
-(void)_willPerformOperation:(id)arg1 forSpecifierUpdates:(id)arg2 ;
-(void)_getSection:(out unsigned*)arg1 row:(out unsigned*)arg2 forSpecifierAtIndex:(unsigned)arg3 forInsertion:(BOOL)arg4 ;
-(void)_didPerformOperation:(id)arg1 forSpecifierUpdates:(id)arg2 ;
-(void)_getSection:(out unsigned*)arg1 row:(out unsigned*)arg2 forSpecifierAtIndex:(unsigned)arg3 forInsertion:(BOOL)arg4 allowGroupSpecifiers:(BOOL)arg5 ;
-(unsigned)_indexOfSpecifierInSection:(unsigned)arg1 row:(unsigned)arg2 forInsertion:(BOOL)arg3 ;
-(id)indexPathForSpecifierAtIndex:(unsigned)arg1 forInsertion:(BOOL)arg2 ;
-(id)indexPathForSpecifierAtIndex:(unsigned)arg1 ;
-(id)specifiersInGroupAtGroupIndex:(unsigned)arg1 ;
-(unsigned)indexOfGroupAtGroupIndex:(unsigned)arg1 ;
-(id)_tabStringOfDepth:(unsigned)arg1 ;
-(void)_appendDescriptionOfArray:(id)arg1 toString:(id)arg2 withTabLevel:(unsigned)arg3 ;
-(unsigned)numberOfRowsInGroupAtIndex:(unsigned)arg1 ;
-(void)_manuallyFindSection:(out unsigned*)arg1 row:(out unsigned*)arg2 forSpecifierAtIndex:(unsigned)arg3 ;
-(id)specifierAtIndexPath:(id)arg1 ;
-(id)indexPathForSpecifierWithID:(id)arg1 ;
-(BOOL)getGroup:(out unsigned*)arg1 row:(out unsigned*)arg2 ofSpecifierWithID:(id)arg3 ;
-(NSRange)rangeOfSpecifiersInGroup:(id)arg1 ;
-(NSRange)rangeOfSpecifiersInGroupWithID:(id)arg1 ;
-(id)specifiersInGroupWithID:(id)arg1 ;
-(unsigned)indexOfGroupWithID:(id)arg1 ;
-(id)_groupSections;
-(id)_synthesizedSpecifiersFromGroupIndex;
@end

