/*
* This header is generated by classdump-dyld 0.7
* on Sunday, November 2, 2014 at 7:50:09 PM Central European Standard Time
* Operating System: Version 8.1 (Build 12B410)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface PSSpecifierAction : NSObject {

	/*^block*/ id _getter;
	/*^block*/ id _setter;

}

@property (nonatomic,copy) id getter;              //@synthesize getter=_getter - In the implementation block
@property (nonatomic,copy) id setter;              //@synthesize setter=_setter - In the implementation block
+(id)actionWithGetter:(/*^block*/ id)arg1 setter:(/*^block*/ id)arg2 ;
+(id)actionWithBoolDetailClass:(Class)arg1 ;
-(id)setter;
-(void)setSetter:(id)arg1 ;
-(void)dealloc;
-(void)setGetter:(id)arg1 ;
-(id)getter;
@end

